---
apiVersion: v1
kind: ConfigMap
metadata:
  name: otelcol-agent
  namespace: kube-system
  labels:
    app.kubernetes.io/name: otelcol
    app.kubernetes.io/instance: k8s-apps
data:
  relay: |
    exporters:
      logging: {}
      otlp/elastic:
        endpoint: ${OTEL_K8S_NODE_IP}:8200
        tls:
          insecure: true
    extensions:
      health_check: {}
    processors:
      k8sattributes:
        extract:
          metadata:
          - container.id
        filter:
          node_from_env_var: OTEL_K8S_NODE_NAME
        passthrough: false
        pod_association:
        - sources:
          - from: resource_attribute
            name: k8s.pod.uid
        - sources:
          - from: resource_attribute
            name: k8s.container.name
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            cors:
              allowed_origins:
              - http://*
              - https://*
            endpoint: 0.0.0.0:4318
    service:
      extensions:
      - health_check
      pipelines:
        logs:
          exporters:
          - logging
          processors:
          - k8sattributes
          receivers:
          - otlp
        metrics:
          exporters:
          - logging
          - otlp/elastic
          processors:
          - k8sattributes
          receivers:
          - otlp
        traces:
          exporters:
          - logging
          - otlp/elastic
          processors:
          - k8sattributes
          receivers:
          - otlp
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: otelcol
  labels:
    app.kubernetes.io/name: otelcol
    app.kubernetes.io/instance: k8s-apps
subjects:
- kind: ServiceAccount
  name: otelcol
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: otelcol
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: otelcol
  labels:
    app.kubernetes.io/name: otelcol
    app.kubernetes.io/instance: k8s-apps
rules:
  - apiGroups: [""]
    resources: ["pods", "namespaces"]
    verbs: ["get", "watch", "list"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: otelcol
  namespace: kube-system
  labels:
    app.kubernetes.io/name: otelcol
    app.kubernetes.io/instance: k8s-apps
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: otelcol
  namespace: kube-system
  labels:
    app.kubernetes.io/name: otelcol
    app.kubernetes.io/instance: k8s-apps
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: otelcol
      app.kubernetes.io/instance: k8s-apps
      component: collector
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: otelcol
        app.kubernetes.io/instance: k8s-apps
        component: collector
    spec:
      serviceAccountName: otelcol
      securityContext:
        {}
      containers:
        - name: opentelemetry-collector
          command:
            - /otelcontribcol
            - --config=/conf/relay.yaml
          securityContext:
            {}
          image: otel/opentelemetry-collector-contrib
          imagePullPolicy: IfNotPresent
          ports:
            - name: otlp-grpc
              containerPort: 4317
              protocol: TCP
              hostPort: 4317
            - name: otlp-http
              containerPort: 4318
              protocol: TCP
              hostPort: 4318
           env:
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
            - name: OTEL_K8S_NODE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: OTEL_K8S_NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
          livenessProbe:
            httpGet:
              path: /
              port: 13133
          readinessProbe:
            httpGet:
              path: /
              port: 13133
          resources:
            limits:
              cpu: 256m
              memory: 512Mi
          volumeMounts:
            - mountPath: /conf
              name: opentelemetry-collector-configmap
      volumes:
        - name: opentelemetry-collector-configmap
          configMap:
            name: otelcol-agent
            items:
              - key: relay
                path: relay.yaml
      hostNetwork: false